godoc:
  host: pkg.go.dev

url: go.pixelfactory.io
packages:
  pkg/observability/log:
    repo: github.com/pixelfactory-go/observability-log
  pkg/server:
    repo: github.com/pixelfactory-go/server
  pkg/version:
    repo: github.com/pixelfactory-go/version
