apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: sally-cert
  namespace: sally
spec:
  commonName: go.pixelfactory.io
  secretName: sally-cert
  dnsNames:
    - go.pixelfactory.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
